### ISSUE TITLE
urban command

### ISSUE THREAD

**Issue by Blotz** [Blotz/gregory#18]
command crashes when searching for anything longer than one word

**Comment by Blotz** [comment]
Dec 08 18:02:54 NasPi python3[29526]: IndexError: list index out of range
Dec 08 18:02:54 NasPi python3[29526]: The above exception was the direct cause of the following exception:
Dec 08 18:02:54 NasPi python3[29526]: Traceback (most recent call last):
Dec 08 18:02:54 NasPi python3[29526]:   File "/home/anais/.local/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 903, in invoke
Dec 08 18:02:54 NasPi python3[29526]:     await ctx.command.invoke(ctx)
Dec 08 18:02:54 NasPi python3[29526]:   File "/home/anais/.local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 859, in invoke
Dec 08 18:02:54 NasPi python3[29526]:     await injected(*ctx.args, **ctx.kwargs)
Dec 08 18:02:54 NasPi python3[29526]:   File "/home/anais/.local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 94, in wrapped
Dec 08 18:02:54 NasPi python3[29526]:     raise CommandInvokeError(exc) from exc
Dec 08 18:02:54 NasPi python3[29526]: discord.ext.commands.errors.CommandInvokeError: Command raised an exception: IndexError: list index out of range
